/**
 * 卡牌配置模块
 * 包含所有角色卡牌和法术卡牌的配置数据
 */

export const CARDS = [
  {
    id: "knight",
    type: "role",
    name: "棉花骑士",
    cost: 2,
    weight: 1.05,
    radius: 26,
    color: "#ff78b8",
    drag: 1.85,
    launchSpeedMul: 1.15,
    effect: "trail",
    life: 16,
    desc: "停下后：冲击波，震开附近怪物。",
    onStop: { kind: "shockwave", cd: 0.75, dmg: 10, radius: 130, knock: 210, maxTriggers: 1 },
  },
  {
    id: "archer",
    type: "role",
    name: "糖霜弓手",
    cost: 3,
    weight: 0.85,
    radius: 23,
    color: "#67d6ff",
    drag: 2.8,
    launchSpeedMul: 1.35,
    effect: "sparkles",
    life: 18,
    desc: "停下后：寒霜箭矢，减速敌人并造成持续伤害。",
    onStop: { kind: "frostArrows", cd: 0.5, dmg: 7, range: 420, slowDuration: 2.5, slowEffect: 0.6 },
  },
  {
    id: "mage",
    type: "role",
    name: "果冻法师",
    cost: 4,
    weight: 0.72,
    radius: 21,
    color: "#a67bff",
    drag: 2.2,
    launchSpeedMul: 0.95,
    effect: "glow",
    life: 17,
    desc: "停下后：法术射线，同时灼烧传送门。",
    onStop: { kind: "beam", cd: 0.8, dmg: 12, range: 520, portalDmg: 7 },
  },
  {
    id: "shield",
    type: "role",
    name: "软糖大盾",
    cost: 3,
    weight: 1.45,
    radius: 30,
    color: "#ffcc57",
    drag: 1.5,
    launchSpeedMul: 0.75,
    effect: "spin",
    life: 24,
    desc: "更重更大：碰撞伤害更高，停下后小范围嘲讽减速。死亡时爆炸造成范围伤害。",
    onStop: { kind: "auraSlow", cd: 0.55, dmg: 6, radius: 120, slow: 0.55 },
  },
  {
    id: "ice",
    type: "spell",
    name: "冰霜结界",
    cost: 4,
    color: "#79f2e1",
    desc: "放置在场地：减速范围内怪物一段时间。",
    spell: { kind: "fieldSlow", duration: 6.5, radius: 170, slow: 0.55 },
    target: "arena",
  },
  {
    id: "fire",
    type: "spell",
    name: "甜辣火球",
    cost: 3,
    color: "#ff8a5b",
    desc: "点选场地位置：爆炸伤害并击退。",
    spell: { kind: "burst", radius: 150, dmg: 18, knock: 240 },
    target: "arena",
  },
  {
    id: "heal",
    type: "spell",
    name: "城墙修补",
    cost: 2,
    color: "#7dff9a",
    desc: "立即回复城墙生命值。(整局游戏限3次)",
    spell: { kind: "healWall", heal: 14 },
    target: "instant",
  },
  {
    id: "charge",
    type: "spell",
    name: "小充能",
    cost: 1,
    color: "#4aa3ff",
    desc: "立即获得法术，并稍微提高当日回复速度。",
    spell: { kind: "chargeMana", gain: 2.5, regenBonus: 0.45, duration: 10 },
    target: "instant",
  },
  {
    id: "hellfire",
    type: "role",
    name: "烈焰法师",
    cost: 5,
    weight: 0.88,
    radius: 22,
    color: "#ff6b35",
    drag: 2.0,
    launchSpeedMul: 1.0,
    effect: "burn",
    life: 19,
    desc: "灼烧攻击：持续性射线，高频伤害数字，灼烧地狱火效果。",
    onStop: { kind: "hellfireBeam", cd: 0.1, baseDmg: 8, maxDmgMul: 3.0, rampTime: 4.0 },
  },
  {
    id: "angel",
    type: "role",
    name: "治愈天使",
    cost: 4,
    weight: 0.65,
    radius: 24,
    color: "#ffd700",
    drag: 1.8,
    launchSpeedMul: 0.9,
    effect: "heal",
    life: 20,
    desc: "停下后：治疗附近队友，若无队友则攻击敌人。",
    onStop: { kind: "angelHeal", cd: 0.6, heal: 3, dmg: 5, radius: 180 },
  },
  {
    id: "bomber",
    type: "role",
    name: "炸弹人",
    cost: 3,
    weight: 0.95,
    radius: 22,
    color: "#ff4444",
    drag: 1.3,
    launchSpeedMul: 1.1,
    effect: "fuse",
    life: 18,
    desc: "自动寻敌：接近敌人自爆造成高额范围伤害。",
    onStop: { kind: "bomberSeek", cd: 0.2, speed: 150, explodeRadius: 120, explodeDamage: 40 },
  },
  {
    id: "joker",
    type: "role",
    name: "疯狂小丑",
    cost: 3,
    weight: 0.45,
    radius: 20,
    color: "#ff00ff",
    drag: 2.5,
    launchSpeedMul: 1.4,
    effect: "chaos",
    life: 14,
    desc: "混乱撞击：让敌人无差别攻击，停止后八方弹射。",
    onStop: { kind: "jokerChaos", cd: 0.8, chaosRadius: 150, bulletDamage: 4 },
  },
  {
    id: "thor",
    type: "role",
    name: "雷神之锤",
    cost: 5,
    weight: 1.15,
    radius: 26,
    color: "#4169e1",
    drag: 1.6,
    launchSpeedMul: 0.95,
    effect: "lightning",
    life: 18,
    desc: "连锁闪电：攻击可能伤害附近多个敌人。",
    onStop: { kind: "thorLightning", cd: 0.7, dmg: 15, chainRadius: 120, chainCount: 3 },
  },
  {
    id: "ninja",
    type: "role",
    name: "暗影忍者",
    cost: 3,
    weight: 0.55,
    radius: 21,
    color: "#2f4f4f",
    drag: 2.0,
    launchSpeedMul: 1.25,
    effect: "shadow",
    life: 16,
    desc: "瞬移打击：快速传送攻击多个目标。",
    onStop: { kind: "ninjaStrike", cd: 0.5, dmg: 8, strikeCount: 3 },
  },
  {
    id: "robot",
    type: "role",
    name: "机械守卫",
    cost: 4,
    weight: 1.35,
    radius: 28,
    color: "#708090",
    drag: 1.2,
    launchSpeedMul: 0.8,
    effect: "mech",
    life: 22,
    desc: "激光炮台：持续扫描攻击直线敌人。",
    onStop: { kind: "robotLaser", cd: 0.3, dmg: 6, laserLength: 400 },
  },
];

// 卡牌稀有度配置（用于抽奖系统）
export const CARD_RARITY = {
  common: ['knight', 'archer', 'mage', 'shield'],
  uncommon: ['ice', 'fire', 'heal', 'charge'],
  rare: ['hellfire', 'angel', 'bomber', 'joker'],
  epic: ['thor', 'ninja', 'robot']
};

// 稀有度权重（用于抽奖概率）
export const RARITY_WEIGHTS = {
  common: 50,
  uncommon: 30,
  rare: 15,
  epic: 5
};
